In [1]:
import numpy as np

In [2]:
a =  np.array([1,2,3])

In [4]:
a[2]

3

In [6]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [7]:
arr = np.full((5,5),1)
arr

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [8]:
arr[1:4, 1:4] = [0,0,0]

In [10]:
arr[2,2] = 9
arr

array([[1, 1, 1, 1, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 9, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 1, 1, 1, 1]])

In [14]:
print(a.ndim)
arr.ndim

1


2

In [15]:
arr.dtype

dtype('int64')

In [17]:
arr.size

25

In [18]:
arr.nbytes

200

In [25]:
arr[:,0:6:2]

array([[1, 1, 1],
       [1, 0, 1],
       [1, 9, 1],
       [1, 0, 1],
       [1, 1, 1]])

In [26]:
np.sum(arr)

25

In [27]:
np.max(arr)

9

In [32]:
np.sum(arr[[0,2,4],:], axis = 1)

array([ 5, 11,  5])

In [46]:
new_arr = arr.reshape((25,1))
new_arr

array([[1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [9],
       [0],
       [1],
       [1],
       [0],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1]])

In [44]:
new_arr

array([[1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [9],
       [0],
       [1],
       [1],
       [0],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1]])

In [49]:
v1 = np.vstack([arr,arr])
v1

array([[1, 1, 1, 1, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 9, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 9, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 1, 1, 1, 1]])